server:
  port: 8002

spring:
  application:
    name: short-link-admin
  datasource:
    username: ieening
    password: n4jz4pdhx4
    url: jdbc:mysql://192.168.2.113:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5